### ISSUE TITLE
Notefield of Main UI loses focus

### ISSUE THREAD

**Issue by JSchraff** [doubleSlashde/KeepTime#88] opened 2021-11-15 08:55 UTC
While typing the notes in the main UI when the mouse isn't hovering ovet the Main UI the textfield loses focus until the mouse hovers over it again.

**Comment by Death111** [comment] 2022-01-02 21:32
As discussed some time ago this is not a bug. I did this on purpose to stop the cursor from blinking in the notes field all day long.
I agree that there may be a nicer solution to this.

**Comment by Death111** [comment] 2022-11-02 16:23
Actually the textArea is not editable anymore on mouse leave (it does not loose focus). See https://github.com/doubleSlashde/KeepTime/blob/aad505c0d4ba69e465be6bb749ba49f8ea7ae440/src/main/java/de/doubleslash/keeptime/view/ViewController.java#L369

**Comment by PhiGegner** [comment] 2023-05-03 09:23
Would be nice to have an option in the settings to enable/disable this behavior.

**Comment by Death111** [comment] 2023-09-18 10:54
A solution which stops the blinking cursor while KeepTime is not active would be sufficient. Maybe there is an "application not in focus anymore" event which we could use instead of the mouse hover event.

**Comment by Death111** [comment] 2023-09-22 07:56
We could remove the previous "workaround" as it now works without it. Looks like it was fixed in some java update :)

**Closed by Death111** 2023-09-22 07:56 UTC
Labels: bug
